server:
  compression:
    enabled: true
    mime-types: application/json
  port: ${PORT:9020}
  servlet:
    context-path: /${spring.application.name}/v${spring.application.majorVersion}

info:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  servlet:
    context-path: /${spring.application.name}/v${spring.application.majorVersion}

spring:
  h2:
    console:
      enabled: true
  application:
    name: koerber
    version: "@project.version@"
    majorVersion: ${APP_VERSION:1}
  datasource:
    url: jdbc:h2:mem:mydb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;IGNORECASE=TRUE;
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        default_schema: KOERBER
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    open-in-view: false
  flyway:
    placeholders:
      bdUser: binding_group
    schemas: KOERBER
    locations: classpath:db/migration

logging:
  level:
    root: INFO

springdoc:
  api-docs:
    path: /swaggers/api-docs
  swagger-ui:
    path: /swaggers/swagger-ui.html
